project:
  type: website
  
filters:
  - webr

website:
  title: "Beyond the ATE - SER 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: instructors.qmd
        text: Instructors
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Welcome!
      - href: info_tldr.qmd
        text: 1. Causal Inference Refresher
      - href: info_d.qmd
        text: 2. Defining Interventions
      - href: info_estimators.qmd
        text: 3. Estimators
      - section: 4. Estimating effects with lmtp
        contents:
          - href: R_data_and_superlearner.qmd
            text: Data Structure and Machine Learning Ensembles
          - href: R_static.qmd
            text: Static effects and the ATE
          - href: R_dynamic.qmd
            text: Dynamic treatment regimes
          - href: R_continuous.qmd
            text: Modified Treatment Policies
          - href: R_survival.qmd
            text: Survival Analysis
          - href: R_advanced.qmd
            text: Advanced Topics
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/nt-williams/lmtp-workshop

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
